name: Build Native

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'CMakeLists.txt'
      - 'src/joltc/**'
      - .github/workflows/build_native.yml
  pull_request:
    paths:
      - 'CMakeLists.txt'
      - 'src/joltc/**'
      - .github/workflows/build_native.yml

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get CMake
      uses: lukka/get-cmake@v3.29.4
      
    - name: Configure win-x64
      run: cmake -S "." -B "build_win_64" -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE:String=Distribution
    - name: Build win-x64
      run: cmake --build build_win_64 --config Distribution

    - name: Configure win-x64 double
      run: cmake -S "." -B "build_win_64_double" -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE:String=Distribution -DDOUBLE_PRECISION=ON
    - name: Build win-x64 double
      run: cmake --build build_win_64_double --config Distribution

    - name: Configure win-arm64
      run: cmake -S "." -B "build_win_arm64" -G "Visual Studio 17 2022" -A ARM64 -DCMAKE_BUILD_TYPE:String=Distribution
    - name: Build win-arm64
      run: cmake --build build_win_arm64 --config Distribution

    - name: Configure win-arm64 double
      run: cmake -S "." -B "build_win_arm64_double" -G "Visual Studio 17 2022" -A ARM64 -DCMAKE_BUILD_TYPE:String=Distribution -DDOUBLE_PRECISION=ON
    - name: Build win-arm64 double
      run: cmake --build build_win_arm64_double --config Distribution

    - name: Package Windows
      run: |
        mkdir bin/win-x64/native
        mkdir bin/win-arm64/native
        mv build_win_64\bin\Distribution\joltc.dll bin/win-x64/native
        mv build_win_64_double\bin\Distribution\joltc_double.dll bin/win-x64/native
        mv build_win_arm64\bin\Distribution\joltc.dll bin/win-arm64/native
        mv build_win_arm64_double\bin\Distribution\joltc_double.dll bin/win-arm64/native
    - uses: actions/upload-artifact@v4
      with:
        name: libs_windows
        path: bin

  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Get CMake
      uses: lukka/get-cmake@v3.29.4

    # Linux
    - name: CMake Configure (linux-x64)
      run: cmake -S "." -B "build_linux_x64" -G Ninja -DCMAKE_BUILD_TYPE=Distribution
    - name: Build linux-x64
      run: cmake --build build_linux_x64 --config Distribution --verbose --parallel

    # Android
    - name: Setup Android NDK
      id: setup-ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25
        add-to-path: false
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: CMake Configure (android-arm64-v8a)
      run: >
        cmake -S "." -B "build_android_arm64_v8a"
        -DANDROID_ABI=arm64-v8a
        -DCMAKE_BUILD_TYPE=Distribution
        -DANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }}
        -DCMAKE_TOOLCHAIN_FILE="${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake"
    - name: Build (android-arm64-v8a)
      run: cmake --build build_android_arm64_v8a --config Distribution --verbose --parallel

    - name: CMake Configure (android-armeabi-v7a)
      run: >
        cmake -S "." -B "build_android_armeabi_v7a"
        -DANDROID_ABI=armeabi-v7a
        -DCMAKE_BUILD_TYPE=Distribution
        -DANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }}
        -DCMAKE_TOOLCHAIN_FILE="${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake"
    - name: Build (android-armeabi-v7a)
      run: cmake --build build_android_armeabi_v7a --config Distribution --verbose --parallel

    - name: CMake Configure (android-x86_64)
      run: >
        cmake -S "." -B "build_android_x86_64"
        -DANDROID_ABI=x86_64
        -DCMAKE_BUILD_TYPE=Distribution
        -DANDROID_NDK=${{ steps.setup-ndk.outputs.ndk-path }}
        -DCMAKE_TOOLCHAIN_FILE="${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake"
    - name: Build (android-armeabi-v7a)
      run: cmake --build build_android_x86_64 --config Distribution --verbose --parallel

    # Linux and Android artifacts
    - name: Package Linux and Android
      run: |
        mkdir -p bin/linux-x64/native
        mkdir -p bin/android-arm64/native
        mkdir -p bin/android-arm/native
        mkdir -p bin/android-x64/native
        mv build_linux_x64/lib/libjoltc.so bin/linux-x64/native/libjoltc.so
        mv build_android_arm64_v8a/lib/libjoltc.so bin/android-arm64/native/libjoltc.so
        mv build_android_armeabi_v7a/lib/libjoltc.so bin/android-arm/native/libjoltc.so
        mv build_android_x86_64/lib/libjoltc.so bin/android-x64/native/libjoltc.so        
    - uses: actions/upload-artifact@v4
      with:
        name: libs_linux
        path: bin

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get CMake
      uses: lukka/get-cmake@v3.29.4

    - name: Configure osx-universal
      run: cmake -S "." -B "build_osx" -G Ninja -DCMAKE_BUILD_TYPE=Distribution -D"CMAKE_OSX_ARCHITECTURES=x86_64;arm64"
    - name: Build osx-universal
      run: cmake --build build_osx --config Distribution --verbose --parallel

    # macOS artifacts
    - name: package_osx
      run: |
        mkdir -p bin/osx/native
        mv build_osx/lib/libjoltc.dylib bin/osx/native/libjoltc.dylib
    - uses: actions/upload-artifact@v4
      with:
        name: libs_osx
        path: bin

  update_libs:
    name: Update Native Libs
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [windows, linux, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: libs_windows
          path: src/JoltPhysicsSharp/runtimes

      - name: Download linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: libs_linux
          path: src/JoltPhysicsSharp/runtimes

      - name: Download osx artifacts
        uses: actions/download-artifact@v4
        with:
          name: libs_osx
          path: src/JoltPhysicsSharp/runtimes          

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: src/JoltPhysicsSharp/runtimes
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          message: Updated native libs
          committer_name: GitHub Actions
          committer_email: actions@github.com
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            libs_windows
            libs_linux
            libs_osx
